definitions:
  models.FormCreate:
    properties:
      about:
        type: string
      photo:
        type: string
      sphere:
        type: string
      userID:
        type: integer
    type: object
  models.UserCreate:
    properties:
      PWD:
        type: string
      email:
        type: string
      name:
        type: string
      surname:
        type: string
      tg:
        type: string
    type: object
  models.UserLogin:
    properties:
      PWD:
        type: string
      email:
        type: string
    type: object
info:
  contact: {}
paths:
  /form/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: form create
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.FormCreate'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully created form
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create form
      tags:
      - form
  /user/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: user get
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successfully get user
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get user
      tags:
      - user
  /user/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: user create
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.UserCreate'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully created user
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create user
      tags:
      - user
  /user/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: user login
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.UserLogin'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully login user
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login user
      tags:
      - user
swagger: "2.0"
