definitions:
  models.Approve:
    properties:
      ID_Form:
        type: integer
      ID_Team:
        type: integer
      id:
        type: integer
    type: object
  models.ApproveCreate:
    properties:
      ID_Form:
        type: integer
      ID_Team:
        type: integer
    type: object
  models.Form:
    properties:
      ID:
        type: integer
      ID_User:
        type: integer
      about:
        type: string
      email:
        type: string
      name:
        type: string
      photo:
        type: string
      sphere:
        type: string
      surname:
        type: string
      tg:
        type: string
    type: object
  models.FormCreate:
    properties:
      ID_User:
        type: integer
      about:
        type: string
      photo:
        type: string
      sphere:
        type: string
    type: object
  models.TeamCreate:
    properties:
      ID_Kap:
        type: integer
      about:
        type: string
      name:
        type: string
    type: object
  models.UserCreate:
    properties:
      PWD:
        type: string
      email:
        type: string
      name:
        type: string
      surname:
        type: string
      tg:
        type: string
    type: object
  models.UserLogin:
    properties:
      PWD:
        type: string
      email:
        type: string
    type: object
info:
  contact: {}
paths:
  /approve/all:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: Successfully get all approves
          schema:
            items:
              $ref: '#/definitions/models.Approve'
            type: array
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all approves
      tags:
      - approve
  /approve/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: approve create
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.ApproveCreate'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully created approve
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create approve
      tags:
      - approve
  /approve/reject:
    post:
      consumes:
      - application/json
      parameters:
      - description: approve rejected
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.Approve'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully rejected approve
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Reject approve
      tags:
      - approve
  /form/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: form get
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successfully get form
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get form
      tags:
      - form
  /form/all:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: Successfully get all forms
          schema:
            items:
              $ref: '#/definitions/models.Form'
            type: array
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all forms
      tags:
      - form
  /form/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: form create
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.FormCreate'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully created form
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create form
      tags:
      - form
  /team/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: team get
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successfully get team
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get team
      tags:
      - team
  /team/add/{id_team}/{id_user}:
    post:
      consumes:
      - application/json
      parameters:
      - description: add user in team
        in: query
        name: id_team
        required: true
        type: integer
      - description: add user in team
        in: query
        name: id_user
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successfully add user in team
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: AddUserTeam team
      tags:
      - team
  /team/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: team create
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.TeamCreate'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully created team
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create team
      tags:
      - team
  /user/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: user get
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successfully get user
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get user
      tags:
      - user
  /user/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: user create
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.UserCreate'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully created user
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create user
      tags:
      - user
  /user/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: user login
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.UserLogin'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully login user
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login user
      tags:
      - user
swagger: "2.0"
